### ISSUE TITLE
git merge 中的一步法不知道如何使用

### ISSUE THREAD

**Issue by HanleyLee** [xjh22222228/git-manual#4]
在 `README.md` 中,  有这样一句

`或者一步法, 将 feature/v1.0.0 分支的内容合并到 develop       git merge feature/v1.0.0 develop`

我使用 git 也挺久了, 前段时间我也一直在找这样的命令, 一直无果, 今天看到你说这个命令可以将 本分支 merge 到另一个分支上(不需要提前 checkout)

于是我尝试了一下, 发现如果按照作者所说, 那么结果应该是将 feature/v1.0.0 merge 到 develop 上, 但是我得到的结果却是 develop 被 merge 到了 feature/v1.0.0 上, 调整命令的顺序也是一样的结果

希望作者能指点下到底怎么才能 不 checkout 的情况下将本 branch 合并到另一 branch 上, 谢谢

**Comment by xjh22222228** [comment]
Sorry, 文档有误, 合并代码需要checkout， 如果嫌麻烦，可以使用 git alias
